name: optilb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - "-e .[dev,examples]"
      # Uncomment the next line if you need the NOMAD optimizer (requires PyNomadBBO)
      # - ".[nomad]"
